#!/bin/bash

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Change to the script directory
cd "$SCRIPT_DIR"

# Function to check if a command was successful
check_error() {
    if [ $? -ne 0 ]; then
        echo "Error generating typeface variants"
        exit 1
    fi
}

./generate-nerd-fonts picotypepro
check_error

# ./generate-nerd-fonts picotype
# check_error

echo "Successfully generated all typeface variants" 